name: Publish Python Package

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.1

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build twine

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*

      - name: Update README badges
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          CLEAN_VERSION=${VERSION#v}  # remove leading "v"
          echo "Updating README badge for version $CLEAN_VERSION"
          sed -i "s|!\[PyPI\](https://img.shields.io/pypi/v/nigeria-states-lgas).*|![PyPI](https://img.shields.io/pypi/v/nigeria-states-lgas/$CLEAN_VERSION)|" README.md

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git checkout main
          git pull origin main
          git add README.md
          git commit -m "Update PyPI badge to $CLEAN_VERSION" || echo "No changes to commit"
          git push origin main
